substitutions:
  name: lights
  friendly_name: Lights
  area: Kitchen
  project: lights.cct
  version: 1.0
  # frequency: 152Hz # Should translate to 19 bit depth.
  frequency: 610Hz # Should translate to 17 bit depth.

api:
  encryption:
    key: !secret encryption_key
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

packages:
  base:
    url: https://github.com/csobrinho/esphome-projects/
    refresh: 1sec
    files:
      - path: base/esp32-dev.yaml
      - path: addons/io/light_cwww.yaml
        vars: { name: "Upper", dev: "upper", led_cw_pin: GPIO18, led_ww_pin: GPIO5 }
      - path: addons/io/light_cwww.yaml
        vars: { name: "Middle", dev: "middle", led_cw_pin: GPIO23, led_ww_pin: GPIO22 }
      - path: addons/io/light_cwww.yaml
        vars: { name: "Sink", dev: "sink", led_cw_pin: GPIO21, led_ww_pin: GPIO19 }
      - path: addons/io/light_cwww.yaml
        vars: { name: "Wine", dev: "wine", led_cw_pin: GPIO4, led_ww_pin: GPIO2 }
